### ISSUE TITLE
[BUG] Auto Quest Completer

### ISSUE THREAD

**Issue by fanturi** [Ephenia/Pokeclicker-Scripts#194] opened 2022-08-03 06:53 UTC
Hi,

Thank you for your scripts it's very useful !

I have a bug with the auto quest completer there are always quests (2 or 3) which are not selected by the script and when I try to select them they come back automatically as not selected.
To be able to complete them I need to put the script on Off and complete them manually.
I put a screen in attachment
![quest_completer](https://user-images.githubusercontent.com/8436757/182543414-f246a746-2850-4543-acd3-a67ed7ebeb7c.jpg)
.

**Comment by Ephenia** [comment] 2022-08-03 23:52
Duplicate of https://github.com/Ephenia/Pokeclicker-Scripts/issues/180

**Closed** 2022-08-03 23:53 UTC
Labels: duplicate, read the guidelines
