### ISSUE TITLE
Auto Quest filter bug

### ISSUE THREAD

**Issue by EugeneFabre** [Ephenia/Pokeclicker-Scripts#195] opened 2022-08-03 08:50 UTC
The quest filter works in a weird way for me, when I click a specific quest sometimes it does not add it to the active quest types, and instead it activates another quest. Here you can see in the gif that I click already completed quests and somehow it activates another quest. Is this a bug or something coming from my settings?

![Séquence 01_1](https://user-images.githubusercontent.com/80844815/182565989-2d5b9d5d-0e33-436c-a58e-10005fdc056b.gif)

**Comment by Ephenia** [comment] 2022-08-03 23:49
Duplicate of https://github.com/Ephenia/Pokeclicker-Scripts/issues/180

**Closed** 2022-08-03 23:53 UTC
Labels: duplicate, read the guidelines
